title: Tianyi Li's Homepage
page-top-title: Hi! Welcome to Tianyi Li's Homepage
top-section-bg-text: Computational Lithography
home-subtitle: Tianyi Li&ensp;|&ensp;李天羿
copyright-text: '&copy; Tianyi Li 2024-2025. All Rights Reserved.'
